# Because some files are needed by controllers
# in the builddir like .plugin files this
# copies them to the builddir if they don't
# exist so that make distcheck works.
all-local:
	@test -z "$(dist_plugin_DATA)" || \
	 for controller in $(dist_plugin_DATA) ; do \
	   if test -e $(srcdir)/$$controller ; then \
	     if ! test -e $(builddir)/$$controller ; then \
	       cp -p $(srcdir)/$$controller $(builddir)/ ; \
	     fi ; \
	   fi ; \
	 done

clean-local:
	@rm -f gschemas.compiled ; \
	 test -z "$(dist_plugin_DATA)" || \
	 test $(srcdir) = $(builddir) || \
	 for controller in $(dist_plugin_DATA) ; do \
	   if test -e $(builddir)/$$controller ; then \
	     rm -f $(builddir)/$$controller ; \
	   fi ; \
	 done
